#!/usr/bin/env bash

set -e
set -o pipefail

usage()
{
    cat - >&2 <<END
Usage: $0 [-m N] [-Dv] pid [...]
    -v: be verbose (print debug information)
    -m N: unwind no more than N frames
    -D: do not demangle symbols
END
    
    exit 64
}

UNWIND_OPTS=

while getopts vm:Dh o
do
  case "$o" in
    D) NODEMANGLE=1 ;;
    m) UNWIND_OPTS="-m $OPTARG" ;;
    v) VERBOSE=1    ;;
    *) usage        ;;
  esac
done

shift $(($OPTIND-1))
[ $# -ge 1 ] || usage


[[ ! $NODEMANGLE ]] && which c++filt >/dev/null 2>&1 || {
    echo "c++filt(1) not found (part of GNU binutils). Demangling will be unavailable" >&2
    NODEMANGLE=1
}

DIR=$( dirname "$0" )

while [ $# -ne 0 ]; do
    pid=$1
    echo -n $pid:
    cat /proc/$pid/cmdline
    echo

    cmd="$DIR/unwind $UNWIND_OPTS -- $pid | perl $DIR/parse_stack.pl $pid"
    [[ $VERBOSE ]]    || cmd="$cmd | grep -v '^\*\*\*'"
    [[ $NODEMANGLE ]] || cmd="$cmd | c++filt"
    eval $cmd

    echo
    shift
done
